project:
  type: website
  output-dir: docs

website:
  title: "My Blog"
  navbar:
    background: '#BEDDBA'
    title: false
    left: 
      - text: "Home"
        href: ../
      - text: "Projects"
        href: ../projects
      - text: "Blog"
        file: index.qmd
      - text: "Contact"
        href: ../contact.html
    tools:
      - icon: github
        menu:
          - text: Source Code
            href:  https://github.com/Paulogcd/blog
          - text: Report a Bug
            href:  https://github.com/Paulogcd/blog/issues

link-external-newwindow: true

format:
  html:
    theme: cosmo
    css: styles.css

